### ISSUE TITLE
Neue Kategorie

### ISSUE THREAD

**Issue by designpilot** [trilobit-gmbh/contao-tiles-bundle#1]
Nach klick auf Neue Kategorie erhalte ich folgende Fehlermeldung:

**Internal Server Error**
`An exception occurred while executing 'INSERT INTO tl_tiles (`tstamp`) VALUES (0)': SQLSTATE[HY000]: General error: 1364 Field 'webappDescription' doesn't have a default value`

wie kann ich das Problem lösen? Die Erweiterung wäre nämlich genial.

System: Contao 4.4.26
PHP: Version 7.2
Installationsart: frische Installation (clean)

**Comment by trilobit-gmbh** [comment]
Hallo, ich habe die Feld-Definition geändert. Bitte schauen Sie, ob es - nach einem Datenbank-Update - jetzt funktioniert.
Können sie ggf noch die Datenbank-Konfiguration hier festhalten (Type, Kollation, MySQL, MariaDB, ...).
Vielen Dank.
Über kurzes Feedback würde ich mich freuen.

Viele Grüße
Peter Adelmann, trilobit GmbH

**Comment by designpilot** [comment]
Hallo, nun funktioniert die Erweiterung und ich kann die neue Kategorie erstellen. Die DB Konfiguration ist bei mir im Moment wie folgt (lokale Entwicklungsumgebung unter macOS X High Sierra)

Apache 2.4 / MySQL 5.5.5-10.3.9-MariaDB / MyISAM / Zeichensatz: UTF-8 Unicode / Kollation: utf8_unicode_ci

**_Habe da noch ein paar Fragen_**
- Wenn ich die Einstellungen für die Elternseite auf den Startpunkt lege, dann wird das denke ich mir global für alle Seiten übernommen korrekt ?
- Wenn ich das Zielverzeichnis auswähle, werden dann in diesem die verschiedenen Icons generiert ?
- Wie funktioniert das mit der WebApp genau ?
- Was ist der Unterschied der verschiedenen Statusleisten bei iOS ?
- Wie funktioniert das mit den Windows Einstellungen genau ?
- Favicon Update forcieren (verstehe ich das richtig, das wenn versch. Motive wie Weihnachten, Ostern hat das dann so aktualisiert wird) ?
- Wie wird denn definiert wie der Hintergrund des Icons / Touch Icons bei Smartphones ist (z.B. die Icon Farbe usw.)
