### ISSUE TITLE
Kein Apple Touch Icon

### ISSUE THREAD

**Issue by designpilot** [trilobit-gmbh/contao-tiles-bundle#2]
Hallo 
Es wird zwar ein Apple Touch Icon generiert das habe ich geprüft, aber wenn ich die WebSite zum Homescreen hinzufügen möchte wird einfach nur ein Bildausschnitt der WebSite angezeigt, die Icons für Apple Touch werden aber im Quellcode eingebunden das verwundert mich eben.

![homebildschirm](https://user-images.githubusercontent.com/5730020/46581014-68c85300-ca30-11e8-8dd1-50a5564044ac.jpg)

Hingegen bei Favoriten oder Lesezeichen hinzufügen funktioniert die Anzeige der Icons ohne Probleme.

![favoriten](https://user-images.githubusercontent.com/5730020/46581029-90b7b680-ca30-11e8-8e17-6564994d202c.jpg)

![lesezeichen](https://user-images.githubusercontent.com/5730020/46581031-9a411e80-ca30-11e8-96df-f0251369a967.jpg)

Wie kann das behoben werden? 

Weil ich habe testweise die Erweiterung **_ma3xl3/contao-easy-favicon_** installiert obwohl eine Warnung bei der Installation mit dem Contao Manager kam das schon eine Version für php-ico installiert sei und diese genutz werde.

Dann habe ich einfach nur für das **_Apple Touch Icon_** das Icon generiert und siehe da, das Apple Touch Icon wird für die Anzeige Homescreen angezeigt, das einzig negative dabei ist dass das Icon schwarz hinterlegt ist und dann nur die Schrift **my** und das **Herbstblatt** angezeigt wird da das Dach des Hauses schwarz ist.

**Comment by trilobit-gmbh** [comment]
Hallo,
welche iOS-Version wird verwendet auf welchem Gerät?
Kannst Du mir das Set der funktionierenden Icons packen und zuschicken (peter.adelmann@trilobit.de)?
Hast Du eine Bspl-Seite die ich erreichen kann und schauen kann, ob es bei der Einbindung noch weitere Probleme/Unterschiede gibt?

Dann kann ich gerne schauen, was ergänzt bzw geändert werden muss, damit die Icons korrekt eingebunden werden.

Zur Erweiterung "ma3xl3/contao-easy-favicon" kann ich nichts sagen. Die Verwendung von "php-ico" werde ich anpassen.

Dass das Icon schwarz hinterlegt wird kann an der Ausgangsgrafik liegen. Hier scheint der automatische Bild-Bearbeitungs-Prozess Probleme mit der Transparenz haben.

Viele Grüße
Peter Adelmann

**Comment by designpilot** [comment]
Hallo Peter

Aktuell habe ich die Erweiterung auf www.myhome-services.ch im Einsatz, was müsstest Du denn noch genau wissen.

Die Icons werden alle korrekt soweit ich sehen kann generiert, das einzige was eben nicht korrekt eingebunden/angezeigt wird ist jenes wenn ich das Icon als Homescreen Icon auf dem iPhone anlegen will es wird dann wie im Screenshot auf Github angezeigt.

Smartphone: iPhone X
iOS Version: 12.0

Freundliche Grüsse
Didier

Von meinem iPhone X gesendet

**Comment by trilobit-gmbh** [comment]
Update verfügbar.
