### ISSUE TITLE
No tiles generate

### ISSUE THREAD

**Issue by robvis** [trilobit-gmbh/contao-tiles-bundle#3]
Guten Tag,

I installed favicon-Tiles, but I don't get it working.
The icons are generate in my given directory, but not visable on the sreen in the preview, only small icons, but no pictures.
Furthermore I have an error message in my log file.
The favicon-196x196.png is available in the directory, so I don't know what page can't be found.
Hope you can help me out.
Regards,
Rob Vis

**ERROR MESSAGE:**
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://slagererikvis.bcd-internetdiensten.nl/files/export/favicon-196x196.png?t=1575718573" at /home/orthom/slagererikvis.bcd-internetdiensten.nl/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: http://slagererikvis.bcd-internetdiensten.nl/files/export/favicon-196x196.png?t=1575718573 at /home/orthom/slagererikvis.bcd-internetdiensten.nl/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: http://slagererikvis.bcd-internetdiensten.nl/files/export/favicon-196x196.png?t=1575718573 at /home/orthom/slagererikvis.bcd-internetdiensten.nl/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:63)"} []

**Comment by trilobit-gmbh** [comment]
Hello Rob,
can you please write me some system details? Also as a personal message directly to peter.adelmann@trilobit.de

- Contao version?
- PHP version?
- Are the generated tiles displayed in the backend file manager?
- Is this folder public?
- Have the symlinks been updated?

The page not found exception is based on a 404 error when calling each tile. Here the system can not find the files in question.

**Comment by trilobit-gmbh** [comment]
checked for clean installations (c4.4, c4.8); OK function
