### ISSUE TITLE
PHP8 / Contao 4.13 LTS

### ISSUE THREAD

**Issue by sdahlmann** [trilobit-gmbh/contao-tiles-bundle#5]
Kurze Frage: Ist es geplant, dass "contao-tiles-bundle" mit PHP 8.x kompatibel zu machen? Wird es kompatibel mit Contao 4.13 LTS sein? Vielen Dank für die Antwort schon im Voraus.

**Comment by trilobit-gmbh** [comment]
Ja, wir planen unsere Bundles fit für PHP 8 und die nächste LTS-Version von Contao (4.13) zu machen.
Wenn Du Zeit und Lust hast freuen wir uns über einen Pull-Request hierzu ;-)

Leider kann ich im Moment aber nicht sagen, wie schnell wir das hin bekommen. Die Umsetzung wird in der Regel sein in
- freien Zeitslots ;-(
- wenn wir es selbst in einer neueren Version benötigen
- wenn es einen Pull-Request gibt ;-)
- wenn wir dafür bezahlt werden ;-)

Viele Grüße
Peter

**Comment by mibrume** [comment]
Hallo Peter,

wollte auch nur sagen, dass eure Extension toll ist und ich es trotzdem kaum erwarten kann, bis sie kompatibel ist.

Lieben Gruß

Michael

**Comment by fritzmg** [comment]
@mibrume wenn du es kaum erwarten kannst, wie du selbst sagst, dann kannst du die Entwickler (oder andere Entwickler) ja gegen Bezahlung damit beauftragen.

**Comment by marcel-mathias-nolte** [comment]
You can evaluate my fixes:

Add this to your composer.json:
`
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/marcel-mathias-nolte/contao-tiles-bundle"
		}
	]`

Select the build "dev-nolte" in contao-manager by clicking the cog wheel:

![image](https://user-images.githubusercontent.com/2349435/154847055-bcbb3fe1-9eaf-42f2-b81e-deea83b40582.png)

It works for me on Contao 4.13 using PHP 8.1

**Comment by trilobit-gmbh** [comment]
see:1.1.0
