### ISSUE TITLE
PHP Warning:  Undefined array key "deleteConfirm" in ...dca/tl_tiles.php

### ISSUE THREAD

**Issue by bizon1** [trilobit-gmbh/contao-tiles-bundle#9]
I'm using
Contao 4.13.12
PHP 8.1.12
trilobit-gmbh/contao-tiles-bundle 1.1.0

Ever if I'm clearing and warming up the Symfony-Cache I get the following PHP Warning:
`PHP Warning:  Undefined array key "deleteConfirm" in .../vendor/trilobit-gmbh/contao-tiles-bundle/src/Resources/contao/dca/tl_tiles.php on line 73`

Changing Line 73 with
`'attributes' => 'onclick="if (!confirm(\''. ($GLOBALS['TL_LANG']['MSC']['deleteConfirm'] ?? null) . '\')) return false; Backend.getScrollOffset();"',`
solved this issue. Perhaps you can fix your bundle too. THX for this extension.

**Comment by trilobit-gmbh** [comment]
see 1.1.1

**Comment by bizon1** [comment]
Thanks for fixing!
